import express from 'express'
import { body } from 'express-validator'
import { protect } from '../middleware/auth.js'
import { validate } from '../middleware/validate.js'
import { asyncHandler } from '../middleware/errorHandler.js'
import User from '../models/User.js'

const router = express.Router()

// Guard: user must have an active subscription
const requireSubscription = asyncHandler(async (req, res, next) => {
  const user = await User.findById(req.user.id)
  if (!user) return res.status(404).json({ message: 'User not found' })
  if (user.subscriptionStatus !== 'active') {
    return res.status(403).json({ message: 'Active subscription required. Please upgrade your plan.' })
  }
  next()
})

/**
 * GET /api/ai/secure-ai
 * Basic premium AI access check.
 */
router.get('/secure-ai', protect, requireSubscription, (req, res) => {
  res.json({ result: 'Phu AI Premium Access Granted' })
})

/**
 * POST /api/ai/codegen
 * AI Code Generation — "automatic coding script writing" feature.
 *
 * Body:
 *   prompt   {string}  – plain-language description of the code to generate
 *   language {string}  – target programming language (default: "javascript")
 *
 * In a real deployment this would call an LLM API (e.g. OpenAI).
 * The response shape is kept stable so the frontend can depend on it.
 */
router.post(
  '/codegen',
  protect,
  requireSubscription,
  [
    body('prompt')
      .isString().trim()
      .isLength({ min: 10, max: 2000 })
      .withMessage('Prompt must be between 10 and 2000 characters'),
    body('language')
      .optional()
      .isString().trim()
      .isIn(['javascript', 'typescript', 'python', 'go', 'rust', 'java', 'csharp', 'php', 'ruby', 'bash'])
      .withMessage('Unsupported language')
  ],
  validate,
  asyncHandler(async (req, res) => {
    const { prompt, language = 'javascript' } = req.body

    // Production: replace the block below with an actual LLM call, e.g.:
    //   const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY })
    //   const completion = await openai.chat.completions.create({ ... })
    //   const code = completion.choices[0].message.content

    const code = generatePlaceholderCode(prompt, language)

    res.json({
      language,
      prompt,
      code,
      generatedAt: new Date().toISOString()
    })
  })
)

/**
 * Placeholder code generator.
 * Returns a commented stub so the API contract is testable without an LLM key.
 */
function generatePlaceholderCode(prompt, language) {
  const commentChar = ['python', 'ruby', 'bash'].includes(language) ? '#' : '//'
  return [
    `${commentChar} Auto-generated by Phu AI Code Generator`,
    `${commentChar} Language : ${language}`,
    `${commentChar} Task     : ${prompt.slice(0, 120)}${prompt.length > 120 ? '...' : ''}`,
    `${commentChar}`,
    `${commentChar} TODO: Connect OPENAI_API_KEY in backend/.env to enable full LLM code generation.`,
    `${commentChar} Until then, this stub shows the expected response envelope.`
  ].join('\n')
}

export default router
